<a href="https://colab.research.google.com/github/IrfanPavel/Tensorflow-Deep-Learning/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
print(tf.__version__)

2.7.0


# **Creating The Tensors with tf.constant()**

In [ ]:
#Create a scalar (rank 0 tensor)
scalar=tf.constant(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
#Create A Vector (more than 0 dimensions)
vector=tf.constant([10,10])
vector

In [ ]:
vector.ndim

In [ ]:
#Create a matrix (more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

In [ ]:
matrix.ndim

In [ ]:
another_matrix=tf.constant([[10.,7.],
                    [7.,10.],
                    [8.,9.]],dtype=tf.float16)
another_matrix

In [ ]:
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

In [ ]:
tensor.ndim

# **A tensor can have arbitary(unlimited) amount of dimensions.**
# For Example,Turning a a series of Images into tensors with shape(224,224,3,32)

# .224,224 (The first 2 dimensions ) are the height and width of the images in pixels
# .3 is the no. of colour channels of the image(red,green,blue)
# .32 is the batch size(The number of images a neural network sees at any one time)

# Tensors-An n-dimensional array of numbers (where n can be any number,a 0 dimension tensor is a scalar,a 1 dimension tensor is a vector)

# **Creating Tensors with tf.variable()**

# **tf.Constant-->Immutable**
# **tf.variable-->Mutable**

In [ ]:
#Create the same tensor with tf.Variable() and tf.constant()

changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

In [ ]:
changeable_tensor[0]=7
changeable_tensor

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

# **Creating Random Tensors**

In [ ]:
#Create two random tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

random_1,random_2,random_1==random_2


In [ ]:
#Create two random tensors
random_1=tf.random.Generator.from_seed(11)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(11)
random_2=random_2.normal(shape=(3,2))

random_1,random_2,random_1==random_2


# **Other ways to make tensors**

In [ ]:
#Make a tensor of all ones
tf.ones(shape=(3,2))

In [ ]:
#Make a tensor of all zeros
tf.zeros(shape=(3,2))

In [ ]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)

A=tf.constant(numpy_A,shape=[2,4,3])
numpy_A,A

Getting Information From Tensors(shape,rank,size)

Shape:The length(number of elements) of each of the dimensions of a tensor

Rank: The number of tensor dimensions(Scalar rank-0,Vector Rank-1,Matrix rank-2,Tensor rank-n)

Axis or Dimension: A particular dimension of a tensor

Size: The total number of items in Tensor

In [ ]:
#Create a rank 4 Tensors

rank_4_tensor=tf.zeros([2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

In [ ]:
#Get various attributes of Tensor
print("Datatype of every elements {}".format(rank_4_tensor.dtype))
print("No. of dimensions (rank) {}".format(rank_4_tensor.ndim))
print("Shape of Tensor {}".format(rank_4_tensor.shape))
print("Elements along axis 0 of Tensor {}".format(rank_4_tensor.shape[0]))
print("Elements along last axis of tensor {}".format(rank_4_tensor.shape[-1]))
print("Total no of elements  {}".format((tf.size(rank_4_tensor).numpy())))

In [ ]:
rank_4_tensor

In [ ]:
#Get The first 2 items of each dimensions
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])

In [ ]:
rank_2_tensor

In [ ]:
#Get The last item of each row
rank_2_tensor[:,-1]

In [ ]:
#Add an extra Dimensions
rank_3_tensors=rank_2_tensor[...,tf.newaxis]
rank_3_tensors

In [ ]:
#Expand
tf.expand_dims(rank_2_tensor,axis=-1) #-1 means last axis

# **Manipulating Tensors(tensor operations)**

# **Basic Operations**

In [ ]:
#Add values to a tensor using the addition operator
tensor=tf.constant([[10,7],[3,4]])
tensor

In [ ]:
tensor+10

In [ ]:
tensor*10

In [ ]:
tf.multiply(tensor,10)

# **Matrix Manipulation**

In [ ]:
print(tensor)

In [ ]:
tf.matmul(tensor,tensor)

In [ ]:
tensor @ tensor

In [ ]:
#(3,2)
X=tf.constant([[1,2],
               [3,4],
               [5,6]])

Y=tf.constant([[7,8],
               [9,10],
               [11,12]])

In [ ]:
X @ Y

In [ ]:
X @ tf.reshape(Y,shape=(2,3))

In [ ]:
#Transpose
tf.transpose(X)


In [ ]:
tf.matmul(tf.transpose(X),Y)

In [ ]:
tf.matmul(a=X,b=Y,transpose_a=True,transpose_b=False)

# **Changing The DataType of a tensor**

In [ ]:
B=tf.constant([1,7,7.4])

In [ ]:
B.dtype

tf.float32

In [ ]:
B=tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1. , 7. , 7.4], dtype=float16)>

In [ ]:
B.dtype

tf.float16

In [ ]:
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [5]:
import numpy as np

In [ ]:
E=tf.constant(np.random.randint(low=0,high=100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 4, 36, 38,  5, 17, 99, 89, 83, 97, 30,  0, 96, 71, 44, 16, 95, 19,
       64, 31, 36, 60, 30, 92, 70,  0,  4, 96, 64, 60, 26, 34, 10, 20, 77,
       30, 85, 87, 80, 11, 60, 53, 75, 32, 43, 39, 70, 83, 26, 69, 44])>

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2500>

# **Finding The positional Maximum and Minimum**

Finding The position of a tensor where the max value occurs

In [ ]:
F=tf.constant(np.random.random(50))
F

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

# **Squeezing a tensor(Removing all single Dimensions)**

In [ ]:
G=tf.constant(np.random.randint(0,100,50),shape=(1,1,1,1,50))
G.shape,G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
G_sqz=tf.squeeze(G)

G_sqz.shape, G_sqz.ndim

(TensorShape([50]), 1)

# **One_Hot Encoding()**

In [ ]:
some_list=[0,1,2,3]
# some_list=["orange","apple","Grapes","Red"]

#One hot encode them

tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify custom value for an off encoding

tf.one_hot(some_list,depth=4,on_value="We're Alive",off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're Alive", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're Alive", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're Alive", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're Alive"]], dtype=object)>

# **Squaring,log,square Root**

In [ ]:
H=tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
tf.sqrt(H)

In [ ]:
#Change H to float32
H=tf.cast(H,dtype=tf.float32)

In [ ]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Manipultaing tf.variable tensors

# **.Assign()-Assign a different value to a particular index of a variable tensor**

# **.add_assign()-Add to an existing value and reassign it at a particular index of a variable tensor** 

In [ ]:
#Create a Variable Tensor
I=tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
#assign the final value a new value of 50
I.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
I.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [ ]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

# **Tensors and Numpy**

# **.np.array()-pass a tensor to convert to an ndarray**
# **.tensor.numpy()-call on a tensor to convert to an ndarray**

In [ ]:
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy()

array([ 3.,  7., 10.])

# **@tf.function**

In [6]:
#Create a simple function
def function(x,y):
  return x**2+y
x=tf.constant(np.arange(0,10))
y=tf.constant(np.arange(10,20))
function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [7]:
#Create the same function and decorate it with tf.function
@tf.function
def tf_function(x,y):
  return x**2+y

function(x,y)



<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

# **Finding Access to GPUs**

In [8]:
print(tf.config.list_physical_devices("GPU"))

[]


In [1]:
import tensorflow as tf
print(tf.config.list_physical_devices("GPU"))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [2]:
!nvidia-smi

Thu Dec 23 17:20:04 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8    28W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------